# Welcome to Serverless!
# Happy Coding!

service: hello

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-3

  include:
  - utils/**
plugins:
- serverless-offline
functions:
  globalRouter:
    handler: handler.globalRouter
    events:
    - http:
        path: /{any+}
        method: ANY